services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    env_file:
      - credentials.env
    volumes:
      - /big_data_1/postgres_data:/var/lib/postgresql
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped

#  rabbitmq:
#    image: rabbitmq:management
#    container_name: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    environment:
#      RABBITMQ_DEFAULT_USER: guest
#      RABBITMQ_DEFAULT_PASS: guest
#    volumes:
#      - rabbitmq_data:/var/lib/rabbitmq

  discord_bot:
    build:
      context: ./discord_bot
    container_name: discord_bot
    volumes:
      - ./shared_resources:/shared_resources/:ro
      - ./discord_bot/resources:/resources
    env_file:
      - path: ./token.env
        required: true
      - path: ./credentials.env
        required: true
    environment:
      - SPRING_PROFILE=prod
    depends_on:
      - postgres
    ports:
      - "8082:8082"
    networks:
      - app-network
    restart: unless-stopped

  server_tracker:
    build:
      context: ./tracker
    container_name: tracker
    volumes:
#      - ./tracker/resources:/resources
      - ./shared_resources:/shared_resources/:ro
    depends_on:
      - postgres
    ports:
      - "8084:8084"
    env_file:
      - path: ./credentials.env
        required: true
    restart: unless-stopped

  google_api_handler:
    build:
      context: ./google_api_handler
    container_name: google_api_handler
    volumes:
      - ./shared_resources:/shared_resources/
      - ./google_token:/tokens
    depends_on:
      - postgres
    ports:
      - "8083:8083"
    env_file:
      - path: ./credentials.env
        required: true
    restart: unless-stopped

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  app-network:
    driver: bridge
