server:
  port: 8081

spring:
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:192.168.1.2}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    virtual-host: ${SPRING_RABBITMQ_VIRTUAL_HOST:/}

  profiles:
    active: prod

  datasource:
    url: ${SPING_DATASOURCE_URL:jdbc:postgresql://192.168.1.2:5432/thousand_uncles_db}
    username: ${SPRING_DATASOURCE_URL:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:mypassword}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jta:
    enabled: true