server:
  port: 8081

spring:
  config:
    import: optional:file:./resources/config.yaml

  datasource:
    url: jdbc:postgresql://192.168.1.2:5432/thousand_uncles_db
    username: admin
    password: mypassword

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:192.168.1.2}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    virtual-host: ${SPRING_RABBITMQ_VIRTUAL_HOST:/}

  profiles:
    active: prod