server:
  port: 8081

spring:
  config:
    import: optional:file:./resources/config.yaml

  datasource:
    url: jdbc:postgresql://192.168.1.2:5432/thousand_uncles_db
    username: admin
    password: mypassword

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:176.118.193.254}
    port: ${SPRING_RABBITMQ_PORT:27500}
    username: ${SPRING_RABBITMQ_USERNAME:pelicanadmin}
    password: ${SPRING_RABBITMQ_PASSWORD:gMwPR85*PkOpcGek@jnTeX&Z}
    virtual-host: ${SPRING_RABBITMQ_VIRTUAL_HOST:/}

  profiles:
    active: prod